name: CI

on:
  push:
    branches:
    - master

jobs:
  jest_coverage:
    name: jest
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
         node-version: '12.x'
      - run: yarn install
      - run: yarn test:coverage
      
  
 
